-- Supabase Schema for Voice Control Feature

-- 1. voice_quota table: Tracks remaining voice command quota for each user
CREATE TABLE IF NOT EXISTS public.voice_quota (
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    remaining_count integer NOT NULL DEFAULT 0,
    last_updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 2. voice_commands_logs table: Logs every voice command attempt
CREATE TABLE IF NOT EXISTS public.voice_commands_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    platform text NOT NULL, -- 'ios' or 'android'
    command text NOT NULL,
    confidence numeric(4, 3) NOT NULL, -- Confidence score (e.g., 0.950)
    timestamp timestamp with time zone DEFAULT now() NOT NULL,
    success boolean NOT NULL,
    meta jsonb -- Additional metadata (e.g., raw text, error code)
);

-- Optional: Enable Row Level Security (RLS)
ALTER TABLE public.voice_quota ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.voice_commands_logs ENABLE ROW LEVEL SECURITY;

-- RLS Policies for voice_quota
-- Users can see and update their own quota
CREATE POLICY "Users can view their own quota" ON public.voice_quota
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own quota" ON public.voice_quota
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- RLS Policies for voice_commands_logs
-- Users can insert and view their own logs
CREATE POLICY "Users can insert their own logs" ON public.voice_commands_logs
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own logs" ON public.voice_commands_logs
  FOR SELECT USING (auth.uid() = user_id);

-- 3. Edge Function Skeleton: handleVoiceEvent
-- This function will be deployed as a Supabase Edge Function (Deno/TypeScript)
-- It should handle the logic for deducting quota and logging the event.
-- The actual implementation will be in TypeScript, this is just a placeholder for the schema.
-- The JS layer will call this function.

-- Example of a function that might be called by the Edge Function to deduct quota (optional, can be done in Edge Function directly)
CREATE OR REPLACE FUNCTION public.deduct_voice_quota(p_user_id uuid, p_deduction_amount integer)
RETURNS integer AS $$
DECLARE
    v_remaining_count integer;
BEGIN
    UPDATE public.voice_quota
    SET remaining_count = remaining_count - p_deduction_amount,
        last_updated_at = now()
    WHERE user_id = p_user_id
    RETURNING remaining_count INTO v_remaining_count;

    IF NOT FOUND THEN
        -- User not found, perhaps insert a new record with a negative count if needed, or raise an error
        RAISE EXCEPTION 'User ID % not found in voice_quota table.', p_user_id;
    END IF;

    RETURN v_remaining_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execution to authenticated users (assuming the Edge Function runs as an authenticated user)
GRANT EXECUTE ON FUNCTION public.deduct_voice_quota(uuid, integer) TO authenticated;
